### ISSUE TITLE
deliver_now warning with rails >= 4.2 

### ISSUE THREAD

**Issue by itkin** [zapnap/resque_mailer#82]
Hello,

Would be cool to alias deliver and new RoR method deliver_now to stick to rails standard (and prevent annoying warning)

**Comment by zapnap** [comment]
Are you seeing an actual deprecation warning when using with Rails 4.2? We're calling the `deliver` method on the `Mail::Message` object, which has not changed (see https://github.com/rails/rails/pull/16582/files for the `deliver_now` PR that addresses this). Let me know if you're seeing something that indicates otherwise.

Regardless, it's probably smart to mirror that Rails API for this. So perhaps it would make more sense to add aliases to map the following:

    deliver_now => deliver!
    deliver_later => deliver

Thoughts?

**Comment by jfragoulis** [comment]
Hi. I am +1 for the aliases. What I would prefer though is to also issue a warning when using those. 

The way I see it, you should not use #deliver with 4.2 (deprecation warning) and you should not use #deliver_now, #deliver_later with 4.2 **and** resque_mailer (also warning). You should either use the one or the other.

**Comment by zapnap** [comment]
Would be happy to take a look at a PR that addresses this if you have the bandwidth!

**Comment by zapnap** [comment]
This should be sorted in latest master.
