### ISSUE TITLE
Support for Rails 5

### ISSUE THREAD

**Issue by gcrofils** [zapnap/resque_mailer#90]
Master branch doesn't work with ActionMailer 5.0.0

`ArgumentError: wrong number of arguments (given 2, expected 0)`

```
from /.../gems/actionmailer-5.0.0/lib/action_mailer/base.rb:582:in `initialize'
from /.../gems/resque_mailer-2.3.1/lib/resque_mailer.rb:121:in `new'
from /.../gems/resque_mailer-2.3.1/lib/resque_mailer.rb:121:in `actual_message'
from /.../gems/resque_mailer-2.3.1/lib/resque_mailer.rb:170:in `deliver!'
```

**Comment by zapnap** [comment]
Correct, Rails 5 support has not yet been added. It's clearly a priority. Please see the conversation on #88

**Comment by zapnap** [comment]
I've created a branch for Rails 5 /zapnap/resque_mailer/tree/rails_5_compat including the appropriate test suite updates.

I'd like to do some more testing on older Rails versions before releasing this. Since the `process` method signature changed in Rails v4.1 I'm assuming this would be a breaking change for users on Rails v4.0 or earlier (derp test stubs).

So it'd either need to be a new major version release or some Rails feature detection code would need to be added.

**Comment by zapnap** [comment]
This has been verified and is being merged to master. Please test your work against the master version of the github project. If everything looks kosher, I'll go ahead and release a new gem. Thanks.

**Comment by MohamedHegab** [comment]
I still have the same issue I am using Rails 5 and it's not sending the mails

**Comment by zapnap** [comment]
Did you try the branch?

**Comment by zapnap** [comment]
If that works for you I'll go ahead and release the update as v2.4.0

**Comment by MohamedHegab** [comment]
Yes, It works when I go to the branch proceed with the update. Thanks
